# Generated by Django 5.2 on 2025-04-16 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_code', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('term_years', models.DecimalField(decimal_places=2, max_digits=4)),
                ('can_be_redeemed', models.BooleanField(default=False)),
                ('other_attributes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=255)),
                ('other_attributes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('other_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_name', models.CharField(max_length=255)),
                ('other_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundBondHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('holding_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_holdings', to='securities.bond')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_holdings', to='securities.fund')),
            ],
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='securities.fundcompany'),
        ),
        migrations.AddField(
            model_name='bond',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='securities.issuer'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='securities.fund')),
            ],
        ),
    ]
