# Generated by Django 5.2 on 2025-04-19 04:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bond',
            name='remaining_term',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='bond',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='contact_email',
            field=models.EmailField(default='unknown@example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='fund',
            name='contact_phone',
            field=models.CharField(default='000-0000-0000', max_length=50),
        ),
        migrations.AddField(
            model_name='fund',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_manager',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='fund',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fundcompany',
            name='company_type',
            field=models.CharField(choices=[('FUND', 'Fund Manager'), ('INSURANCE', 'Insurance Company'), ('BANK', 'Bank'), ('OTHER', 'Other Financial Institution')], default='FUND', max_length=20),
        ),
        migrations.AddField(
            model_name='fundcompany',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fundcompany',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issuer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='issuer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bond',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bond',
            name='term_years',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='fundcompany',
            name='company_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='issuer_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.CreateModel(
            name='BondHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('remaining_term_at_purchase', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('holding_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('is_current_holding', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_holdings', to='securities.bond')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_holdings', to='securities.fund')),
            ],
            options={
                'unique_together': {('fund', 'bond', 'purchase_date')},
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_code', models.CharField(default='', max_length=50)),
                ('search_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('search_result', models.TextField(default='{}')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FundBondHolding',
        ),
    ]
