# Generated by Django 5.2 on 2025-04-19 06:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0003_remove_searchhistory_search_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondholding',
            name='holding_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of fund assets', max_digits=6),
        ),
        migrations.AddField(
            model_name='fundcompany',
            name='aum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Assets under management', max_digits=18),
        ),
    ]
