# Generated by Django 5.2 on 2025-04-21 01:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0004_bondholding_holding_percentage_fundcompany_aum'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bondholding',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bond',
            name='bond_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bond',
            name='coupon_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bond',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bondholding',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_bond_holdings', to='securities.fundcompany'),
        ),
        migrations.AddField(
            model_name='bondholding',
            name='sell_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='securities.fundcompany'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='qq',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='qt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='wechat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='bond_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='query',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='result_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bondholding',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bond_holdings', to='securities.fund'),
        ),
        migrations.AlterField(
            model_name='bondholding',
            name='holding_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of assets', max_digits=6),
        ),
        migrations.AlterField(
            model_name='fund',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fundcompany',
            name='company_type',
            field=models.CharField(choices=[('FUND', '基金公司'), ('WEALTH', '理财公司'), ('BROKER', '券商自营'), ('INSURANCE', '保险公司'), ('BANK', '银行'), ('OTHER', '其他金融机构')], default='FUND', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='securities.fund'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='bond_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='bondholding',
            constraint=models.CheckConstraint(condition=models.Q(('fund__isnull', False), ('company__isnull', False), _connector='OR'), name='holding_must_belong_to_either_fund_or_company'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('company__isnull', False), ('fund__isnull', False), _connector='OR'), name='person_must_belong_to_either_company_or_fund'),
        ),
    ]
